---
- name: Workstation Configuration
  hosts: all
  vars_files:
    - vars/secrets.yml

  roles:
    - role: git
      tags: git
    - role: shell
      tags: shell
    - role: languages
      tags: languages
    - role: desktop
      tags: desktop
    - role: apps
      tags: [apps]
    - role: gaming
      tags: [gaming, apps]
