- name: Server Configuration
  hosts: all
  vars_files:
    - vars/secrets.yml

  roles:
    - role: base
      tags: base
    - role: git
      tags: git
    - role: shell
      tags: shell
    - role: spyglass
      tags: spyglass
