---
- name: Server Configuration
  hosts: all

  roles:
    - role: git
      tags: git
    - role: shell
      tags: shell
    - role: spyglass
      tags: spyglass

  post_tasks:
    - name: Run final state reconciliation
      include_role:
        name: cleanup
        apply:
          tags: [always, cleanup]
      tags: [always, cleanup]
