---
- name: Load OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['distribution'] }}.yml"
    - "{{ ansible_facts['os_family'] }}.yml"
    - "default.yml"

- name: Install GNOME Desktop Environment
  become: true
  ansible.builtin.package:
    name: "{{ desktop_environment_group }}"
    state: present

- name: Ensure default boot is Server Mode (Multi-User)
  become: true
  ansible.builtin.file:
    src: /lib/systemd/system/multi-user.target
    dest: /etc/systemd/system/default.target
    state: link
    force: true

- name: Enable GNOME Dark Mode
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"

- name: Set legacy GTK theme to Dark
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Adwaita-dark'"
