dotfiles_dest: "~/repos/dotfiles"

desktop_packages:
  - ghostty
  - antigravity
  - Sunshine
  - brave-browser
  - uget
  - steam
  - steam-devices

desktop_links:
  - { src: "ghostty", dest: "~/.config/ghostty" }
