---
- name: Install Intel Media Drivers and Utils
  ansible.builtin.dnf:
    name:
      - intel-media-driver
      - libva-intel-driver
      - libva-utils
    state: present
  become: true

- name: Ensure podman is installed
  ansible.builtin.dnf:
    name: podman
    state: present
  become: true

- name: Ensure podman.socket is enabled and running
  ansible.builtin.systemd:
    name: podman.socket
    state: started
    enabled: true
  become: true

- name: Create Wolf config directory
  ansible.builtin.file:
    path: /etc/wolf
    state: directory
    mode: '0755'
  become: true

- name: Deploy Wolf udev rules (Virtual Device Support)
  ansible.builtin.copy:
    content: |
      # Allows Wolf to access /dev/uinput (only needed for joypad support)
      KERNEL=="uinput", SUBSYSTEM=="misc", MODE="0660", GROUP="input", OPTIONS+="static_node=uinput", TAG+="uaccess"

      # Allows Wolf to access /dev/uhid (only needed for DualSense emulation)
      KERNEL=="uhid", GROUP="input", MODE="0660", TAG+="uaccess"

      # Joypads
      KERNEL=="hidraw*",   ATTRS{name}=="Wolf PS5 (virtual) pad", GROUP="root", MODE="0660", ENV{ID_SEAT}="seat9"
      SUBSYSTEMS=="input", ATTRS{name}=="Wolf X-Box One (virtual) pad", GROUP="root", MODE="0660", ENV{ID_SEAT}="seat9"
      SUBSYSTEMS=="input", ATTRS{name}=="Wolf PS5 (virtual) pad", GROUP="root", MODE="0660", ENV{ID_SEAT}="seat9"
      SUBSYSTEMS=="input", ATTRS{name}=="Wolf gamepad (virtual) motion sensors", GROUP="root", MODE="0660", ENV{ID_SEAT}="seat9"
      SUBSYSTEMS=="input", ATTRS{name}=="Wolf Nintendo (virtual) pad", GROUP="root", MODE="0660", ENV{ID_SEAT}="seat9"
    dest: /etc/udev/rules.d/85-wolf-virtual-inputs.rules
    mode: '0644'
  become: true
  notify: Reload udev rules

- name: Deploy Wolf Quadlet container definition
  ansible.builtin.template:
    src: wolf.container.j2
    dest: /etc/containers/systemd/wolf.container
    mode: '0644'
  become: true
  notify:
    - Reload systemd daemon
    - Restart wolf container

- name: Ensure Wolf service is enabled and started
  ansible.builtin.systemd:
    name: wolf
    state: started
    enabled: true
    daemon_reload: true
  become: true

- name: Enforce stable Intel GuC/HuC state (GuC=2)
  ansible.builtin.replace:
    path: /etc/default/grub
    regexp: 'i915\.enable_guc=[0-9]'
    replace: 'i915.enable_guc=2'
  become: true
  notify:
    - Update GRUB config
    - Reboot host

- name: Open Wolf firewall ports
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - 47984/tcp # HTTPS
    - 47989/tcp # HTTP
    - 47999/udp # Control
    - 48010/tcp # RTSP
    - 48100/udp # Video
    - 48200/udp # Audio
  when: ansible_facts['os_family'] == 'RedHat'
