---
- name: Reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Restart PipeWire
  ansible.builtin.systemd:
    name: pipewire
    state: restarted
    scope: user

- name: Restart sunshine-headless
  ansible.builtin.systemd:
    name: sunshine-headless.service
    state: restarted
    scope: user
