---
- name: Add 3rd Party Repositories
  become: true
  ansible.builtin.yum_repository:
    name: "{{ item.key }}"
    description: "{{ item.value.description }}"
    baseurl: "{{ item.value.baseurl }}"
    enabled: "{{ item.value.enabled | default(true) }}"
    gpgcheck: "{{ item.value.gpgcheck | default(true) }}"
    gpgkey: "{{ item.value.gpgkey | default(omit) }}"
  loop: "{{ apps_repos | dict2items }}"
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install Desktop Apps
  become: true
  ansible.builtin.package:
    name: "{{ apps_packages }}"
    state: present

- name: Reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
